config/routes.rb
Rails.application.routes.draw do
  devise_for :users,:controllers => {
 :sessions => 'users/sessions'
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "homes#top"
  get "/about"=>"homes#about"
  get "search" => "posts#search"

  resources :users ,only: [:show, :edit, :update] do
    collection do
      get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
      patch '/users/:id/withdraw' => 'users#withdraw', as: 'withdraw'
    end

     resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
  end


  resources :posts do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :mountains
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :comment, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def create
    @post = Post.find(params[:post_id])
    comment = Comment.new(comment_params)
    comment.post_id = @post.id
    comment.user_id = current_user.id
    comment.save
    # redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @post_comment = Comment.find(params[:id])
    @post_comment.destroy
    # Comment.find_by(id: params[:id], post_id: params[:post_id]).destroy
    # redirect_to post_path(params[:post_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_index.html.erb
<% post.comments.each do |comment| %>
  <% comment_user = comment.user %>
    <tr class="comment-user-profile-box">
      <td class="comment-user-image">
        <%= link_to user_path(comment.user) do %>
          <%= attachment_image_tag comment.user, :profile_image, fallback: "no_image.jpg", class: "comment-image",size:"50x50" %>
        <% end %>
        <p><%= comment_user.name %></p>
      </td> 
      <td class="comment-user-content text-left">
         <%= simple_format(comment.comment) %>
      </td>
      <td class="comment-delete">
        <% if current_user == comment.user %>
    	    <%= link_to '削除', post_comment_path(comment.post_id, comment.id), class: 'btn-sm btn-danger comment-delete',remote: true, method: :delete %>
        <% end %>
      </td>
  </tr>
<% end %>

app/views/comments/create.js.erb
$("#comment_area").html("<%= j(render 'comments/index', post: @post) %>");
$("#form").val("");

app/views/comments/destroy.js.erb
$("#comment_area").html("<%= j(render 'comments/index', post: @post) %>");
$("#form").val("");