config/routes.rb
Rails.application.routes.draw do
  devise_for :users,:controllers => {
 :sessions => 'users/sessions'
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "homes#top"
  get "/about"=>"homes#about"
  get "search" => "posts#search"

  resources :users ,only: [:show, :edit, :update] do
    collection do
      get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
      patch '/users/:id/withdraw' => 'users#withdraw', as: 'withdraw'
    end

     resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
  end


  resources :posts do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :mountains
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image
  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 被フォロー関係を通じて参照→followed_idをフォローしている人

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 【class_name: "Relationship"】は省略可能
  has_many :followings, through: :relationships, source: :followed
  # 与フォロー関係を通じて参照→follower_idをフォローしている人
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  def following?(user)
    followings.include?(user)
  end


  def active_for_authentication?
    super && (self.is_deleted == false)
  end
  
  validates :name, length: { maximum: 20 } ,presence: true
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :reject_user, only: [:create]
  protected


  def reject_user
    @user = User.find_by(email: params[:user][:email].downcase)
    if @user
      if (@user.valid_password?(params[:user][:password]) && (@user.active_for_authentication? == false))
        flash[:alert] = "このアカウントは退会済みです。"
        redirect_to new_user_session_path
      end
    else
      flash[:alert] = "必須項目を入力してください"
      redirect_to new_user_session_path
    end
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user=User.find(params[:id])
    @posts=@user.posts.all
                .order(created_at: :desc) #新しい順に並び替える
                 .page(params[:page]).per(6)
  end

  def edit
    @user =User.find(params[:id])
    if @user == current_user
      render"edit"
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def unsubscribe
    @user = User.find(params[:id])
  end

  def withdraw
    @user = User.find(params[:id])
    @user.update(is_deleted: true)
    reset_session
    flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
    redirect_to about_path
  end

  private

  def user_params
   params.require(:user).permit(:name,:introduction,:profile_image)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_other.html.erb
<div class="user-show-other-image">
  <%= link_to user_path(user) do %>
    <%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", class: "other-image",size: "100x100" %>
  <% end %>
</div>
<div class="user-show-other-box">
  <div class="user-show-other-name">
    <%= user.name %>
  </div>
  <div class="user-show-other-body">
    <%= user.introduction %>
  </div>
</div>

app/views/users/_user_post_index.html.erb
<div class="texts-wrapper container mt-5">
   <div class="contents-title text-center">
     <div class="row">
       <% post.each do |post| %>
         <div class="col-12 col-md-6 col-lg-4 mb-2">
           <div class="card h-100">
             <div>
                <%= link_to post_path(post) do %>
                <%= attachment_image_tag post, :image, fallback: "no_image.jpg",class:"card-img-top index-img img-fluid" %>
                <% end %>
             </div>
             <p class="post-index-user text-left pl-3">
               <span class="text-left">
                  <i class="fas fa-user-circle"></i>
                  <%= post.user.name %>
               </span>
               <span class="pl-3">
                  <i class="far fa-comment"></i>
                   <%= post.comments.count %>
                   <span id="favorite-<%= post.id%>">
                     <%= render "favorites/favorites", post: post %>
                   </span>
                </span>
             </p>
             <div class="post-index-post-tag ">
               <% post.tags.each do |tag| %>
                 <span class="border border-dark rounded p-1 mr-1 small"><%= tag.tag_name%></span>
               <% end %>
             </div>
               <div class="card-body">
                 <p class="card-title font-weight-bold">
                   <%= post.title %>
                 </p>
                 <p class="card-text">
                   <%= post.body.truncate(30) %>
                 </p>
                 <p class="card-text">
                    <time>
                      <%= post.updated_at.strftime("%Y-%m-%d %H:%M") %>
                    </time>
                 </p>
               </div>
           </div>
         </div>
       <% end %>
     </div>
   </div>
   <div class="d-flex align-items-center justify-content-center mt-2">
    <%= paginate post %>
   </div>
</div>

app/views/users/edit.html.erb
<div class="contianer mt-5 mb-5">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>プロフィール編集</h1>
      <%= form_with model:@user ,local:true do |f| %>
        <div class="form-group">
          <lavel for="title">Name</lavel>
          <%= f.text_field :name, class:"form-control user_name" %>
        </div>

        <div class="form-group">
          <lavel for="body">Image</lavel>
          <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
        </div>

        <div class="form-group">
          <lavel for="body">Inroduction</lavel>
          <%= f.text_area :introduction, class:"form-control user_body" %>
        </div>

        <div class="actions">
          <%= f.submit '更新',class:"btn btn-success" %>
          <%= link_to "退会する", unsubscribe_users_path,class:"btn btn-danger ml-5"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container mt-5">
  <div class="row user-show text-center col-8 mx-auto">
    <div class="user-show-content mx-auto mb-5">
      <div class="user-show-image mt-2">
      <%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg",class:"rounded-circle",size: "340x220"%>
      </div>
      <div class="user-deatail">
        <h3><%= @user.name %></h3>
         <p class="text-left"><%= @user.introduction %></p>
         <p>投稿<%= @user.posts.count %></p>
         <p>
            <span class="mr-2">
              <%= link_to user_followings_path(@user.id) do %>
                フォロー<%= @user.followings.count %>
              <% end %>
            </span>
            <span>
              <%= link_to user_followers_path(@user.id) do %>
                  フォロワー<%= @user.followers.count %>
              <% end %>
            </span>
          </p>
      </div>
      <div class="user-follow mb-3">
        <% unless @user == current_user %>
          <% if current_user.following?(@user) %>
            <%= link_to 'フォローを外す', user_relationships_path(@user.id), method: :delete, class:"btn btn-secondary" %>
          <% else %>
            <%= link_to 'フォローする', user_relationships_path(@user.id), method: :POST, class:"btn btn-primary" %>
          <% end %>
        <% end %>
      </div>
      <div>
        <% if @user== current_user %>
          <%= link_to edit_user_path(current_user) do %>
            <button type="button" class="btn btn-default personal-edit-button">
              編集する
            </button>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%= render "users/user_post_index",post: @posts %>

app/views/users/unsubscribe.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto">
      <div>
        <h2 class="text-center my-5">本当に退会しますか？</h2>
        <p>
          退会する場合は、「退会する」をクリックしてください<br>
        </p>
      </div>
      <div class="d-flex justify-content-around mt-5">
        <%= link_to "退会しない",user_path,class:"btn btn-primary"%>
        <%= link_to "退会する",withdraw_users_path,method: :patch,class:"btn btn-danger"%>
      </div>
    </div>
  </div>
</div>