config/routes.rb
Rails.application.routes.draw do
  devise_for :users,:controllers => {
 :sessions => 'users/sessions'
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "homes#top"
  get "/about"=>"homes#about"
  get "search" => "posts#search"

  resources :users ,only: [:show, :edit, :update] do
    collection do
      get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
      patch '/users/:id/withdraw' => 'users#withdraw', as: 'withdraw'
    end

     resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
  end


  resources :posts do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :mountains
end

app/models/post.rb
class Post < ApplicationRecord
   attachment :image

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags


  with_options presence: true do
    validates :title, length: { maximum: 25 }
    validates :body
    validates :image
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def tags_save(tag_list)
    if self.tags != nil
      post_tags_records = PostTag.where(post_id: self.id)
      post_tags_records.destroy_all
    end

    tag_list.each do |tag|
      inspected_tag = Tag.where(tag_name: tag).first_or_create
      self.tags << inspected_tag
    end
  end

  # def self.search(search)
  #   return Post.all unless search
  #   # Post.where(["body ?", "%#{search}%"])
  #   Post.joins(:tags).where(["tag_name ?", "%#{search}%"])
  # end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    tag_list = params[:post][:tag_names].split(",")
    @post.tags_save(tag_list)
    if @post.save
      redirect_to post_path(@post)
    else
      render "new"
    end
  end

  def index
    @posts = Post.all
             .order(created_at: :desc) #新しい順に並び替える
             .page(params[:page]).per(10)
  end

  def edit
    @post = Post.find(params[:id])
    if  @post.user == current_user
      render "edit"
    else
      redirect_to posts_path
    end
  end

  def update
    @post = Post.find(params[:id])
    tag_list = params[:post][:tag_names].split(",")
    @post.tags_save(tag_list)
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render "edit"
    end
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @comments = @post.comments
                     .order(created_at: :desc)
    @comment = current_user.comments.new
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path(post.user)
  end

  def search
      @tag = Tag.find_by(tag_name: params[:search])
      if @tag.present?
        @posts = @tag.posts.page(params[:page]).per(10)
      else
        @posts = Post.where(id:  PostTag.all.pluck('post_id').uniq).page(params[:page]).per(10)
      end
      @value = params[:search]

  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :image)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div class="container">
  <h2 class="text-center my-5">投稿編集</h2>
  <div class="row">
    <div class="col-8 offset-2 mb-5">
      
      <% if @post.errors.any? %>
        <div class="text-danger" role="alert">
          <%= @post.errors.count %>件のエラーが発生しました
          <ul>
            <% @post.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
       
       <%= form_with model:@post ,local:true do |f| %>
      
      <table>
        <tr>
          <div class="form-group">
            <%= f.label :タイトル, class:"form_label" %>
            <%= f.text_field :title, placeholder:"タイトル",class:"form-control mb-3" %>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <%= f.label :投稿内容, class:"form_label" %>
            <%= f.text_area :body, size: "50x5", placeholder:"ここに投稿内容を記述します",class:"form-control form-control-lg mb-3" %>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <%= f.label :タグ %>
            <%= f.text_field :tag_names, placeholder:",で区切ってください" ,class:"form-control mb-3"%>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <%= f.label :画像の選択, class:"form_label"%>
            <%= f.attachment_field :image,class:"mb-3 ml-3"%>
          </div>
        </tr>
        </tr>
        <tr>
        <div class="form-action d-flex justify-content-around">
          <%= f.submit "変更を保存", class:"btn btn-success" %>
          <%= link_to "投稿詳細へ戻る",post_path, class:"btn btn-outline-secondary" %>
        </div>
        </tr>
      <% end %>
      </table>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="texts-wrapper container mt-3">
   <div class="contents-title text-center">
     <h3>投稿一覧</h3>
     <div class="row">
       <% @posts.each do |post| %>
         <div class="col-12 col-md-6 col-lg-4 mb-2">
           <div class="card h-100">
             <div>
                <%= link_to post_path(post) do %>
                <%= attachment_image_tag post, :image, fallback: "no_image.jpg",class:"card-img-top index-img img-fluid" %>
                <% end %>
             </div>
             <p class="post-index-user text-left pl-3">
               <span class="text-left">
                  <i class="fas fa-user-circle"></i>
                  <%= post.user.name %>
               </span>
               <span class="pl-3">
                  <i class="far fa-comment"></i>
                   <%= post.comments.count %>
                   <span id="favorite-<%= post.id%>">
                     <%= render "favorites/favorites", post: post %>
                   </span>
                </span>
             </p>
             <div class="post-index-post-tag ">
               <% post.tags.each do |tag| %>
                 <span class="border border-dark rounded p-1 mr-1 small"><%= tag.tag_name%></span>
               <% end %>
             </div>
               <div class="card-body">
                 <p class="card-title font-weight-bold">
                   <%= post.title %>
                 </p>
                 <p class="card-text">
                   <%= post.body.truncate(30) %>
                 </p>
                 <p class="card-text">
                    <time>
                      <%= post.updated_at.strftime("%Y-%m-%d %H:%M") %>
                    </time>
                 </p>
               </div>
           </div>
         </div>
       <% end %>
     </div>
   </div>
   <div class="d-flex align-items-center justify-content-center mt-2">
    <%= paginate @posts %>
   </div>
 </div>

app/views/posts/new.html.erb
<div class="container">
  <h2 class="text-center my-5">新規登録</h2>
  <div class="row">
    <div class="col-8 offset-2 mb-5">

      <% if @post.errors.any? %>
        <div class="text-danger" role="alert">
          <%= @post.errors.count %>件のエラーが発生しました
          <ul>
            <% @post.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%= form_with model:@post ,local:true do |f| %>

      <table>
        <tr>
          <div class="form-group">
            <%= f.label :タイトル, class:"form_label" %>
            <%= f.text_field :title, placeholder:"タイトル",class:"form-control mb-3" %>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <%= f.label :投稿内容, class:"form_label" %>
            <%= f.text_area :body, size: "50x5", placeholder:"ここに投稿内容を記述します",class:"form-control form-control-lg mb-3" %>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <%= f.label :タグ %>
            <%= f.text_field :tag_names, placeholder:",で区切ってください" ,class:"form-control mb-3"%>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <%= f.label :画像の選択, class:"form_label"%>
            <%= f.attachment_field :image,class:"mb-3 ml-3"%>
          </div>
        </tr>
        </tr>
        <tr>
        <div class="form-action d-flex justify-content-around">
          <%= f.submit "新規登録", class:"btn btn-success" %>
          <%= link_to "戻る",:back, class:"btn btn-outline-secondary" %>
        </div>
        </tr>
      <% end %>
      </table>
    </div>
  </div>
</div>

app/views/posts/search.html.erb
<div class="texts-wrapper container">
   <div class="contents-title text-center">
     <% if @tag.present? %>
     　<h3>"<%= @value %>"の検索結果</h3>
     <% else %>
     　<h3>検索に一致する投稿が見つかりません</h3>
     <% end %>
     <div class="row">
       <% @posts.each do |post| %>
         <div class="col-12 col-md-6 col-lg-4 mb-2">
           <div class="card h-100">
             <div>
                <%= link_to post_path(post) do %>
                <%= attachment_image_tag post, :image, fallback: "no_image.jpg",class:"card-img-top index-img img-fluid" %>
                <% end %>
             </div>
             <p class="post-index-user text-left pl-3">
               <span class="text-left">
                  <i class="fas fa-user-circle"></i>
                  <%= post.user.name %>
               </span>
               <span class="pl-3">
                  <i class="far fa-comment"></i>
                   <%= post.comments.count %>
                   <span id="favorite-<%= post.id%>">
                     <%= render "favorites/favorites", post: post %>
                   </span>
                </span>
             </p>
             <div class="post-index-post-tag ">
               <% post.tags.each do |tag| %>
                 <span class="border border-dark rounded p-1 mr-1 small"><%= tag.tag_name%></span>
               <% end %>
             </div>
               <div class="card-body">
                 <p class="card-title font-weight-bold">
                   <%= post.title %>
                 </p>
                 <p class="card-text">
                   <%= post.body.truncate(30) %>
                 </p>
                 <p class="card-text">
                    <time>
                      <%= post.updated_at.strftime("%Y-%m-%d %H:%M") %>
                    </time>
                 </p>
               </div>
           </div>
         </div>
       <% end %>
     </div>
   </div>
 </div>

 <div class="post-index-pagination">
    <%= paginate @posts %>
 </div>

app/views/posts/show.html.erb
<div class="texts-wrapper">
   <div class="contents-title text-center">
     <hr class="border-line"/>
      <h2 class="text-center">投稿詳細</h2>
     <hr class="border-line"/>
     <h3 class="text-center"><%= link_to @post.user.name,user_path(@post.user_id)%>さんの投稿</h3>
     <div class="row">
         <div class="col-12">
           <div class="card card-show">
             <div>
               <%= attachment_image_tag @post, :image, fallback: "no_image.jpg", class: "card-img-top show-img" %>
             </div>
             <p class="post-index-user text-left pl-3">
               <span class="text-left">
                  <i class="fas fa-user-circle"></i>
                  <%= @post.user.name %>
               </span>
               <span class="pl-3">
                  <i class="far fa-comment"></i>
                   <%= @post.comments.count %>
                   <span id="favorite-<%= @post.id%>">
                     <%= render "favorites/favorites", post: @post %>
                   </span>
                </span>
             </p>
             <div class="post-index-post-tag ">
               <% @post.tags.each do |tag| %>
                 <span class="border border-dark rounded p-1 mr-1 small"><%= tag.tag_name%></span>
               <% end %>
             </div>
               <div class="card-body">
                 <h3 class="card-title text-center">
                    <%= @post.title %>
                 </h3>
                 <p class="card-text">
                   <%= simple_format @post.body %>
                 </p>
                 <p class="card-text">
                    <time>
                      <%= @post.updated_at.strftime("%Y-%m-%d %H:%M") %>
                    </time>
                 </p>
               </div>
           </div>
           <div class="post-show-post-edit">
              <% if @post.user.id == current_user.id %>
                <%= link_to "編集", edit_post_path(@post), class: "btn btn-sm btn-default edit_post_#{@post.id}" %>
                <%= link_to '削除', post_path(@post), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-default destroy_post_#{@post.id}"%>
              <% end %>
            </div>

            <div class="post-show-post-comment-box">
              <div class="post-show-post-comment-title">
                <h3>コメント</h3>
              </div>
              <div class="comments-form">
                <%= form_with model:[@post,@comment] do |f| %>
                  <%= f.text_area :comment, placeholder: "コメントを書こう！", size:"90x2", class: "post-show-comment-form",id: "form" %>
                  <%= f.submit 'コメントする', class: "btn btn-default comment-button" %>
                <% end %>
              </div>
              <table class="comments" id="comment_area">
                  <%= render 'comments/index', post: @post %>
              </table>
            </div>
         </div>
     </div>
   </div>
 </div>