config/routes.rb
Rails.application.routes.draw do
  devise_for :users,:controllers => {
 :sessions => 'users/sessions'
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "homes#top"
  get "/about"=>"homes#about"
  get "search" => "posts#search"

  resources :users ,only: [:show, :edit, :update] do
    collection do
      get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
      patch '/users/:id/withdraw' => 'users#withdraw', as: 'withdraw'
    end

     resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
  end


  resources :posts do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :mountains
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/mountain.rb
class Mountain < ApplicationRecord
  belongs_to :user
  attachment :mountain_image
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
# 　geocoded_byが入力した住所から緯度経度を保存。
# 　after_validation :geocodeは後に住所変更があっても、変更後の緯度経度を保存してくれる。

  with_options presence: true do
    validates :mountain_name, length: { maximum: 25 }
    validates :mountain_body
    validates :address
  end

end

app/models/post.rb
class Post < ApplicationRecord
   attachment :image

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags


  with_options presence: true do
    validates :title, length: { maximum: 25 }
    validates :body
    validates :image
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def tags_save(tag_list)
    if self.tags != nil
      post_tags_records = PostTag.where(post_id: self.id)
      post_tags_records.destroy_all
    end

    tag_list.each do |tag|
      inspected_tag = Tag.where(tag_name: tag).first_or_create
      self.tags << inspected_tag
    end
  end

  # def self.search(search)
  #   return Post.all unless search
  #   # Post.where(["body ?", "%#{search}%"])
  #   Post.joins(:tags).where(["tag_name ?", "%#{search}%"])
  # end
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/relationship.rb
class Relationship < ApplicationRecord
 belongs_to :follower, class_name: "User"
 belongs_to :followed, class_name: "User"
 
 validates :follower_id, presence: true
 validates :followed_id, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags
  has_many :posts, through: :post_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image
  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 被フォロー関係を通じて参照→followed_idをフォローしている人

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 【class_name: "Relationship"】は省略可能
  has_many :followings, through: :relationships, source: :followed
  # 与フォロー関係を通じて参照→follower_idをフォローしている人
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  def following?(user)
    followings.include?(user)
  end


  def active_for_authentication?
    super && (self.is_deleted == false)
  end
  
  validates :name, length: { maximum: 20 } ,presence: true
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end
  
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    tag_list = params[:post][:tag_names].split(",")
    @post.tags_save(tag_list)
    if @post.save
      redirect_to post_path(@post)
    else
      render "new"
    end
  end

  def index
    @posts = Post.all
             .order(created_at: :desc) #新しい順に並び替える
             .page(params[:page]).per(10)
  end

  def edit
    @post = Post.find(params[:id])
    if  @post.user == current_user
      render "edit"
    else
      redirect_to posts_path
    end
  end

  def update
    @post = Post.find(params[:id])
    tag_list = params[:post][:tag_names].split(",")
    @post.tags_save(tag_list)
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render "edit"
    end
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @comments = @post.comments
                     .order(created_at: :desc)
    @comment = current_user.comments.new
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path(post.user)
  end

  def search
      @tag = Tag.find_by(tag_name: params[:search])
      if @tag.present?
        @posts = @tag.posts.page(params[:page]).per(10)
      else
        @posts = Post.where(id:  PostTag.all.pluck('post_id').uniq).page(params[:page]).per(10)
      end
      @value = params[:search]

  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :image)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user=User.find(params[:id])
    @posts=@user.posts.all
                .order(created_at: :desc) #新しい順に並び替える
                 .page(params[:page]).per(6)
  end

  def edit
    @user =User.find(params[:id])
    if @user == current_user
      render"edit"
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def unsubscribe
    @user = User.find(params[:id])
  end

  def withdraw
    @user = User.find(params[:id])
    @user.update(is_deleted: true)
    reset_session
    flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
    redirect_to about_path
  end

  private

  def user_params
   params.require(:user).permit(:name,:introduction,:profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/mountains_helper.rb
module MountainsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
       <p><%= flash[:notice] %></p>
<% end %>
<% if flash[:alert] %>
       <p class="text-danger"><%= flash[:alert] %></p>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <p class="text-center">©Remount</p>
</footer>

app/views/layouts/_header.html.erb
<header class="shadow-sm">
  <nav class="navbar navbar-expand-lg navbar-light">
    <% if user_signed_in? %>
      <%= link_to "Remount",root_path, class:"header-title navbar-brand" %>
      <%= form_tag(search_path,:method => 'get') do %>
        <%= text_field_tag(:search, nil, placeholder: "\uf02c タグで検索", class: 'fa fa-xs')%>
        <%= submit_tag 'Search', :name => nil %>
      <% end %>
      <button class="navbar-toggler mx-5" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
        <ul class="navbar-nav">
         <li class="nav-item">
           <%= link_to "マイページ",user_path(current_user),class:"btn btn-outline-secondary mx-3 my-1" %>
         </li>
         <li class="dropdown">
           <button class="btn btn-outline-secondary mx-3 my-1 dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
              一覧
              <span class="caret"></span>
           </button>
           <ul>
             <div class="dropdown-menu" aria-labelledby="dropdownMenu1">
               <li><%= link_to "投稿一覧", posts_path,class:"btn btn-default dropdown-item" %></li>
               <li><%= link_to "山一覧", mountains_path,class:"btn btn-default dropdown-item" %></li>
             </div>
           </ul>
         </li>

         <li class="dropdown">
           <button class="btn btn-outline-secondary mx-3 my-1 dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
              投稿
              <span class="caret"></span>
           </button>
           <ul>
             <div class="dropdown-menu" aria-labelledby="dropdownMenu1">
               <%= link_to "投稿する", new_post_path,class:"btn btn-default dropdown-item" %>
               <%= link_to "山追加", new_mountain_path,class:"btn btn-default dropdown-item" %>
             </div>
           </ul>
         </li>

         <li class="nav-item">
           <%= link_to "ログアウト",destroy_user_session_path,method: :delete,class:"btn btn-outline-secondary mx-3 my-1" %>
         </li>
        </ul>
      </div>

    <% else %>
       <%= link_to "Remount",root_path, class:"header-title navbar-brand" %>
       <button class="navbar-toggler mx-5" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
       </button>
       <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
        <ul class="navbar-nav">
         <li class="nav-item">
           <%= link_to "about",about_path,class:"btn btn-outline-secondary mx-3 my-1" %>
         </li>

         <li class="nav-item">
           <%= link_to "新規登録",new_user_registration_path,class:"btn btn-outline-secondary mx-3 my-1" %>
         </li>

         <li class="nav-item">
           <%= link_to "ログイン",new_user_session_path,class:"btn btn-outline-secondary mx-3 my-1" %>
         </li>
        </ul>
      </div>
    <% end %>

  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Remount</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <div id="wrapper">
    <%= render "layouts/header"%>
     <main>
       <div id="flash">
        <%= render "layouts/flash" %>
       </div>
       <%= yield %>
     </main>
    <%= render "layouts/footer"%>
    </div>
  </body>
</html>